/**
 * Harness I/O — persist AutoHarness artifacts to the task directory.
 *
 * Files written:
 *   - `harness.js` — LLM-synthesized validation function (executable code)
 *   - `harness-verdict.yaml` — latest verdict (score, issues, accepted)
 *
 * The harness.js file is the key artifact from AutoHarness (arXiv:2603.03329):
 * the LLM generates a validation **function**, not a list of rules. This function
 * runs deterministically at evaluation time — no LLM in the loop.
 *
 * Persisting as .js enables:
 *   - Inspection: devs can read/edit the generated validation logic
 *   - Caching: skip re-synthesis on retry (config.cache)
 *   - Harness-as-policy: the file can be checked in and reused permanently
 *   - Debugging: add console.log, run standalone, step through with debugger
 *
 * The harness-verdict.yaml file enables:
 *   - Progress tracking: see score progression across attempts
 *   - Debugging: inspect which rules passed/failed and why
 *   - Tree search (Phase 3): scores inform branch selection
 */

import { join } from 'node:path';
import { readFileSync, writeFileSync, unlinkSync, existsSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { readYaml, writeYaml } from './yaml-io.ts';

/* ------------------------------------------------------------------ */
/*  Types                                                              */
/* ------------------------------------------------------------------ */

/** Single issue in the verdict */
export interface VerdictIssueEntry {
  message: string;
  severity: 'error' | 'warning';
  file?: string;
  line?: number;
}

/** On-disk shape of harness-verdict.yaml */
export interface HarnessVerdictYaml {
  /** When this verdict was produced */
  evaluatedAt: string;
  /** Attempt number (1-based) */
  attempt: number;
  /** Whether the verdict accepted the output */
  accepted: boolean;
  /** 0-1 heuristic score */
  score: number;
  /** Issues found */
  issues: VerdictIssueEntry[];
  /** History of past verdicts (appended on each evaluation) */
  history?: Array<{
    evaluatedAt: string;
    attempt: number;
    accepted: boolean;
    score: number;
    issueCount: number;
  }>;
}

/* ------------------------------------------------------------------ */
/*  File constants                                                     */
/* ------------------------------------------------------------------ */

const HARNESS_FILE = 'harness.js';
const VERDICT_FILE = 'harness-verdict.yaml';

/* ------------------------------------------------------------------ */
/*  Read / Write: harness.js (synthesized validation function)         */
/* ------------------------------------------------------------------ */

/**
 * Read cached harness code from the task directory.
 * Returns null if no harness.js exists.
 */
export function readHarnessCode(taskDir: string): string | null {
  const filePath = join(taskDir, HARNESS_FILE);
  if (!existsSync(filePath)) return null;
  return readFileSync(filePath, 'utf-8');
}

/**
 * Write synthesized harness code to the task directory.
 *
 * The file includes a metadata header comment with synthesis timestamp
 * and source config, followed by the executable function body.
 */
export function writeHarnessCode(
  taskDir: string,
  code: string,
  source: { from?: string; prompt?: string },
): void {
  mkdirSync(taskDir, { recursive: true });

  const header = [
    '// Auto-generated by AutoHarness (arXiv:2603.03329)',
    `// Synthesized at: ${new Date().toISOString()}`,
    ...(source.from ? [`// Source: ${source.from}`] : []),
    ...(source.prompt ? [`// Prompt: ${source.prompt.slice(0, 100)}${source.prompt.length > 100 ? '...' : ''}`] : []),
    '//',
    '// This function runs with: file.read, file.exists, file.glob, shell.run, issues.push',
    '// Edit freely — changes are preserved across retries unless .harness({ refinable: true })',
    '',
  ].join('\n');

  writeFileSync(join(taskDir, HARNESS_FILE), header + code + '\n', 'utf-8');
}

/**
 * Clear cached harness code (e.g., when refinable harness is re-synthesized).
 */
export function clearHarnessCode(taskDir: string): void {
  const filePath = join(taskDir, HARNESS_FILE);
  if (existsSync(filePath)) {
    unlinkSync(filePath);
  }
}

/* ------------------------------------------------------------------ */
/*  Read / Write: harness-verdict.yaml (evaluation results)            */
/* ------------------------------------------------------------------ */

/**
 * Read the latest harness verdict from the task directory.
 * Returns null if no verdict exists.
 */
export function readHarnessVerdict(taskDir: string): HarnessVerdictYaml | null {
  return readYaml<HarnessVerdictYaml>(join(taskDir, VERDICT_FILE));
}

/**
 * Write a harness verdict to the task directory.
 * Appends the previous verdict to the history array for score tracking.
 */
export function writeHarnessVerdict(
  taskDir: string,
  verdict: {
    attempt: number;
    accepted: boolean;
    score: number;
    issues: VerdictIssueEntry[];
  },
): void {
  const existing = readHarnessVerdict(taskDir);
  const now = new Date().toISOString();

  // Build history: carry forward existing history + previous verdict
  const history: HarnessVerdictYaml['history'] = [];
  if (existing?.history) {
    history.push(...existing.history);
  }
  if (existing) {
    history.push({
      evaluatedAt: existing.evaluatedAt,
      attempt: existing.attempt,
      accepted: existing.accepted,
      score: existing.score,
      issueCount: existing.issues.length,
    });
  }

  const data: HarnessVerdictYaml = {
    evaluatedAt: now,
    attempt: verdict.attempt,
    accepted: verdict.accepted,
    score: verdict.score,
    issues: verdict.issues,
    ...(history.length > 0 ? { history } : {}),
  };

  writeYaml(join(taskDir, VERDICT_FILE), data);
}
