/**
 * Unit tests for harness I/O (harness.js code persistence, harness-verdict.yaml)
 */

import { describe, it, expect, beforeEach } from 'vitest';
import { mkdtempSync, existsSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  readHarnessCode,
  writeHarnessCode,
  clearHarnessCode,
  readHarnessVerdict,
  writeHarnessVerdict,
} from '../../../src/store/fs/harness-io.ts';

let taskDir: string;

beforeEach(() => {
  taskDir = mkdtempSync(join(tmpdir(), 'harness-io-'));
});

/* ------------------------------------------------------------------ */
/*  harness.js — synthesized validation function                       */
/* ------------------------------------------------------------------ */

describe('harness.js (code persistence)', () => {
  it('returns null when no harness.js exists', () => {
    expect(readHarnessCode(taskDir)).toBeNull();
  });

  it('writes and reads back synthesized code', () => {
    const code = 'const content = await file.read("src/Nav.tsx");\nif (!content.includes("export default")) {\n  issues.push({ message: "Missing default export", severity: "error" });\n}';

    writeHarnessCode(taskDir, code, { from: 'task-prompt' });

    const loaded = readHarnessCode(taskDir);
    expect(loaded).not.toBeNull();
    // Should contain the original code
    expect(loaded).toContain('await file.read("src/Nav.tsx")');
    expect(loaded).toContain('issues.push');
  });

  it('includes metadata header in persisted file', () => {
    writeHarnessCode(taskDir, '// test code', { from: 'inputs', prompt: 'Check exports' });

    const raw = readFileSync(join(taskDir, 'harness.js'), 'utf-8');
    expect(raw).toContain('Auto-generated by AutoHarness');
    expect(raw).toContain('arXiv:2603.03329');
    expect(raw).toContain('Synthesized at:');
    expect(raw).toContain('Source: inputs');
    expect(raw).toContain('Prompt: Check exports');
    expect(raw).toContain('// test code');
  });

  it('persists as a .js file (executable, inspectable)', () => {
    writeHarnessCode(taskDir, 'issues.push({ message: "test", severity: "error" });', {});

    expect(existsSync(join(taskDir, 'harness.js'))).toBe(true);
    // Should NOT create harness.yaml
    expect(existsSync(join(taskDir, 'harness.yaml'))).toBe(false);
  });

  it('clears cached code', () => {
    writeHarnessCode(taskDir, '// test', {});
    expect(readHarnessCode(taskDir)).not.toBeNull();

    clearHarnessCode(taskDir);
    expect(readHarnessCode(taskDir)).toBeNull();
    expect(existsSync(join(taskDir, 'harness.js'))).toBe(false);
  });

  it('clearHarnessCode is no-op when file does not exist', () => {
    clearHarnessCode(taskDir); // Should not throw
  });

  it('truncates long prompt in header', () => {
    const longPrompt = 'A'.repeat(200);
    writeHarnessCode(taskDir, '// test', { prompt: longPrompt });

    const raw = readFileSync(join(taskDir, 'harness.js'), 'utf-8');
    expect(raw).toContain('...');
    // Header should not include the full 200-char prompt
    expect(raw.split('\n')[0].length).toBeLessThan(200);
  });
});

/* ------------------------------------------------------------------ */
/*  harness-verdict.yaml — evaluation results                          */
/* ------------------------------------------------------------------ */

describe('harness-verdict.yaml (verdict persistence)', () => {
  it('returns null when no verdict exists', () => {
    expect(readHarnessVerdict(taskDir)).toBeNull();
  });

  it('writes and reads back a verdict', () => {
    writeHarnessVerdict(taskDir, {
      attempt: 1,
      accepted: false,
      score: 0.5,
      issues: [
        { message: 'Missing export', severity: 'error' },
        { message: 'No responsive', severity: 'warning' },
      ],
    });

    const loaded = readHarnessVerdict(taskDir);
    expect(loaded).not.toBeNull();
    expect(loaded!.attempt).toBe(1);
    expect(loaded!.accepted).toBe(false);
    expect(loaded!.score).toBe(0.5);
    expect(loaded!.issues).toHaveLength(2);
    expect(loaded!.evaluatedAt).toBeTruthy();
  });

  it('builds history across multiple verdicts', () => {
    writeHarnessVerdict(taskDir, {
      attempt: 1, accepted: false, score: 0.3,
      issues: [{ message: 'Build failed', severity: 'error' }],
    });

    writeHarnessVerdict(taskDir, {
      attempt: 2, accepted: false, score: 0.6,
      issues: [{ message: 'Missing type', severity: 'error' }],
    });

    writeHarnessVerdict(taskDir, {
      attempt: 3, accepted: true, score: 1.0, issues: [],
    });

    const loaded = readHarnessVerdict(taskDir);
    expect(loaded!.attempt).toBe(3);
    expect(loaded!.accepted).toBe(true);
    expect(loaded!.history).toHaveLength(2);
    expect(loaded!.history![0].attempt).toBe(1);
    expect(loaded!.history![0].score).toBe(0.3);
    expect(loaded!.history![1].attempt).toBe(2);
    expect(loaded!.history![1].score).toBe(0.6);
  });
});
